# Краткий обзор понятий теории вероятностей

## События

**Пространством элементарных событий** $\Omega$ называется множество, содержащее все возможные результаты случайного эксперимента, из которых в эксперименте происходит ровно один. Элементы $\omega$ этого множества называют элементарными исходами.

**Событиями** называются подмножества множества $\Omega$. Говорят, что в результате эксперимента произошло событие $A\subseteq \Omega$, если в эксперименте произошел один из элементарных исходов, входящих в множество $A$.

**Достоверным** называется событие, которое обязательно происходит в результате эксперимента, т.е. единственное событие, включающее все элементарные исходы --- событие $\Omega$.

**Невозможным** называется событие, которое не может произойти в результате эксперимента, т.е. событие, не содержащее ни одного элементарного исхода. Всегда $\emptyset\subset \Omega$.

**Суммой** $A+B$ или объединением $A\cup B$ событий $A$ и $B$ называется событие, состоящее в том, что произошло либо событие $A$, либо событие $B$, либо оба события одновременно, т.е. множество $A+B$ содержит элементарные исходы, входящие либо в множество $A$, либо в $B$ или в оба.

**Умножением** $AB$ или пересечением $A\cap B$ событий $A$ и $B$ называется событие, состоящее в том, что произошли оба события $A$ и $B$ одновременно, т.е. множество $AB$ содержит элементарные исходы, входящие одновременно и в множество $A$, и в множество $B$.

**Дополнением** $A\backslash B$ события $B$ до $A$ называется событие, состоящее в том, что произошло событие $A$, но не произошло $B$, т.е. множество $A\backslash B$ содержит элементарные исходы, входящие в множество $A$, но не входящие в $B$.

**Противоположным** к событию $A$ называется событие $\bar A =\Omega\backslash A$, состоящее в том, что событие $A$ в результате эксперимента не произошло, т.е. множество $\bar A$ состоит из элементарных исходов, не входящих в $A$.

Говорят, что несколько событий образует **полную группу событий**, если в результате опыта непременно должно появиться хотя бы одно из них.

События $A$ и $B$ называются **несовместными**, если их совместное появление невозможно, т.е. $AB = \emptyset$.

## Вероятность события, аксиоматика Колмогорова

Множество $\mathcal{F}$, элементами которого являются подмножества множества $\Omega$ называется сигма-алгеброй, если выполнены следующие условия:

1.  сигма-алгебра содержит достоверное событие $\Omega \in \mathcal{F}$;

2.  вместе с любым событием сигма-алгебра содержит противоположное событие: если $A\in \mathcal{F}$, то и $\bar A\in \mathcal{F}$;

3.  вместе с любым счётным набором событий сигма-алгебра содержит их объединение: если $A_1, A_2, A_3,\ldots \in \mathcal{F}$, то $\displaystyle{\bigcup_{i=1}^\infty A_i \in \mathcal{F}}$.

**Вероятностью** или **вероятностной мерой** на $(\Omega, \mathcal{F})$ называется функция $P:\mathcal{F}\rightarrow R$, удовлетворяющая аксимомам:

1.  для любого события $A\in \mathcal{F}$ выполняется неравенство $P(A)\geq 0$;

2.  для любого счётного набора попарно несовместных событий $C_1, C_2, C_3,\ldots \in \mathcal{F}$ имеет место равенство $\displaystyle{P\left(\bigcup_{i=1}^\infty C_i\right) =\sum_{i=1}^\infty P(C_i)}$;

3.  вероятность достоверного события равна единице $P(\Omega)=1$.

## Теоремы вероятностей

Событие $A$ называется **независимым** от события $B$, если вероятность события $A$ не зависит от того, произошло событие $B$ или нет. Событие $A$ называется зависимым от события $B$, если вероятность события $A$ меняется в зависимости от того, произошло событие $B$ или нет.

**Условной вероятностью** события $P(A|B)$ события $A$ называется вероятность появления этого события, вычисленная в предположении, что имело место событие $B$.

**Теорема умножения** Вероятность произведения двух событий равна произведению вероятности одного из них на условную вероятность другого, вычисленную при условии, что первое имело место $P(AB) =P(A)P(B|A)$

Если $A$ не зависит от $B$, то и $B$ не зависит от $A$. Говорят, что события независимы.

**Теорема сложения** Для любых событий $A$ и $B$ вероятность суммы событий $P(A+B) = P(A)+P(B)-P(AB)$

**Формула полной вероятности** Вероятность события $A$, которое может наступить лишь при появлении одного из несовместных событий $H_1,H_2,\ldots,H_n$, образующих полную группу событий, равна $\displaystyle{P(A)=\sum_{k=1}^n P(H_k)P(A|H_k)}$, где $\displaystyle{\sum_{k=1}^n P(H_k)=1}$ **Формула Байеса** Пусть событие $A$ может наступить лишь при условии появления одного из несовместных событий (гипотез) $H_1,H_2,\ldots,H_n$, образующих полную группу событий. Если событие $A$ уже произошло, то вероятности гипотез могут быть переоценены по формуле Байеса $\displaystyle{P(H_k|A)=\frac{P(H_k)P(A|H_k)}{P(A)}}$, где $\displaystyle{P(A)=\sum_{i=1}^n P(H_i)P(A|H_i)}$


## Выберите все подходящие ответы из списка

1. Пусть один раз подбрасывается игральный кубик. Событие AA - выпадение четной грани, событие BB - выпадение грани с 4 очками. Тогда событие C= A+BC=A+B заключается в том, что выпадают четные грани

2. При однократном бросании монеты события "выпадение герба" и "выпадение решки" являются несовместными

3. Пусть один раз из игральной колоды в 36 карт вытаскивается 1 карта. Событие $A$ - выпадение карты бубновой масти, событие $B$ - выпадение туза. Тогда событие $C= AB$ заключается в том, что выпадает бубновый туз

4. Если события $A$ и $B$ независимы, то $P(AB)=P(A)P(B)$

7. Пусть один раз из игральной колоды в 36 карт вытаскивается 1 карта. Событие $A$ - выпадение карты бубновой масти, событие $B$ - выпадение туза. Тогда вероятность события $D= A+B$ равна 1/3

# Вероятностное пространство и случайная величина